.github/workflows/pr-test-npu.yml, .pre-commit-config.yaml, scripts/npu_ci_install_dependency.sh, test/srt/test_ascend_attention_backend.py
=> [CI] Add NPU PR workflow

.github/workflows/pr-test-npu.yml, scripts/npu_ci_install_dependency.sh
Some PR will failed due to bad network connection when access data from github, this PR preload the file using our cache server
=> chore: download related file from cache

.github/workflows/release-docker-ascend-nightly.yml, docker/Dockerfile.npu
add nightly docker image publish workflow
=> feat: add docker image workflow

.github/workflows/release-docker-ascend-nightly.yml
=> fix: image tag

python/sglang/srt/layers/moe/ep_moe/layer.py, python/sglang/srt/layers/quantization/w8a8_int8.py, python/sglang/srt/model_executor/cuda_graph_runner.py, python/sglang/srt/model_executor/model_runner.py, python/sglang/srt/models/deepseek_v2.py
support ep-moe on npu
python\sglang\srt\layers\moe\ep_moe\layer.py: add a forward_npu function in Class EPMoE
=> support ep-moe on npu

python/sglang/srt/layers/moe/ep_moe/layer.py, python/sglang/srt/layers/quantization/w8a8_int8.py
=> feat: add dequant swiglu quant

python/sglang/srt/layers/moe/ep_moe/layer.py
=> bugfix: index_select index out of range when seq is more than 1920

python/sglang/srt/disaggregation/utils.py, python/sglang/srt/layers/attention/ascend_backend.py, python/sglang/srt/layers/attention/mla_preprocess.py, python/sglang/srt/layers/attention/torch_native_backend.py, python/sglang/srt/layers/rotary_embedding.py, python/sglang/srt/mem_cache/memory_pool.py, python/sglang/srt/model_executor/model_runner.py, python/sglang/srt/models/deepseek_v2.py
=> feat: dsv3 接入mlapo

docker/Dockerfile.npu
=> feat: install deep-ep in Dockerfile.npu

.github/workflows/pr-test-npu.yml, scripts/npu_ci_install_dependency.sh, test/srt/test_ascend_mla_w8a8int8.py, test/srt/test_ascend_tp1_bf16.py, test/srt/test_ascend_tp2_bf16.py
=> [CI] Change CI Testcases

docker/Dockerfile.npu
=> fix: using libascend_hal.so temporarily

sgl-router/src/policies/buckets.rs
=> add init boundary log

python/sglang/srt/managers/data_parallel_controller.py
=> Modified Round-Robin strategy

python/sglang/srt/model_executor/cuda_graph_runner.py, python/sglang/srt/model_executor/npu_graph_runner.py
=> bugfix: thread of npu_graph

docker/Dockerfile.npu
=> fix: build sglang based on sglang-npu repo

python/sglang/srt/disaggregation/prefill.py, python/sglang/srt/layers/attention/ascend_backend.py, python/sglang/srt/layers/attention/torch_native_backend.py, python/sglang/srt/managers/schedule_batch.py, python/sglang/srt/mem_cache/allocator.py, python/sglang/srt/mem_cache/memory_pool.py, python/sglang/srt/mem_cache/radix_cache.py
This reverts commit e44a0e68745723134a5a21833bfeb75fdfcfe118.
=> Revert "change Req token to cpu (#57)"

docker/Dockerfile.npu, python/sglang/srt/managers/data_parallel_controller.py, python/sglang/srt/managers/scheduler.py, python/sglang/srt/server_args.py, sgl-router/py_src/sglang_router/launch_router.py, sgl-router/src/config/types.rs, sgl-router/src/policies/buckets.rs, sgl-router/src/policies/factory.rs
=> dp controller args check

python/sglang/srt/managers/data_parallel_controller.py
=> dp controller load balance

python/sglang/srt/layers/attention/ascend_backend.py, python/sglang/srt/layers/attention/mla_preprocess.py, python/sglang/srt/layers/rotary_embedding.py, python/sglang/srt/mem_cache/memory_pool.py, python/sglang/srt/model_executor/model_runner.py, python/sglang/srt/models/deepseek_v2.py
=> feat: prefill fa and decoder mlapo

python/sglang/srt/distributed/parallel_state.py, python/sglang/srt/layers/attention/ascend_backend.py, python/sglang/srt/layers/quantization/w8a8_int8.py, python/sglang/srt/model_executor/cuda_graph_runner.py, python/sglang/srt/model_executor/model_runner.py, python/sglang/srt/model_executor/npu_graph_runner.py
=> npu support graph

python/sglang/srt/layers/attention/ascend_backend.py, python/sglang/srt/model_executor/forward_batch_info.py, python/sglang/srt/model_executor/npu_graph_runner.py
=> opt: prefill fa atb->fia

python/sglang/srt/disaggregation/ascend/conn.py, python/sglang/srt/disaggregation/utils.py, python/sglang/srt/layers/attention/ascend_backend.py, python/sglang/srt/layers/attention/mla_preprocess.py, python/sglang/srt/mem_cache/memory_pool.py, python/sglang/srt/model_executor/npu_graph_runner.py, python/sglang/srt/models/deepseek_v2.py
=> support kv separation

python/sglang/srt/layers/attention/ascend_backend.py, python/sglang/srt/layers/quantization/w8a8_int8.py, python/sglang/srt/managers/schedule_batch.py, python/sglang/srt/mem_cache/allocator.py, python/sglang/srt/model_executor/npu_graph_runner.py, python/sglang/srt/models/deepseek_nextn.py, python/sglang/srt/models/deepseek_v2.py, python/sglang/srt/speculative/build_eagle_tree.py, python/sglang/srt/speculative/eagle_draft_cuda_graph_runner.py, python/sglang/srt/speculative/eagle_draft_extend_cuda_graph_runner.py, python/sglang/srt/speculative/eagle_draft_extend_npu_graph_runner.py, python/sglang/srt/speculative/eagle_draft_npu_graph_runner.py, python/sglang/srt/speculative/eagle_utils.py, python/sglang/srt/speculative/eagle_worker.py
=> support mtp

python/sglang/srt/layers/moe/ep_moe/layer.py, python/sglang/srt/layers/moe/token_dispatcher/deepep.py
=> feat:support DeepEP normal mode
